### ISSUE TITLE
Hacking Hairstyles

### ISSUE THREAD

**Issue by BrittanyG1150** [Prodigy-Hacking/ProdigyMathGameHacking#564] opened 2021-02-28 23:00 UTC
**Describe the hack in 5 words or less:** Hacking Hairstyle Hack 

**Have you made sure this hack isn't available yet?* (Yes/No)** No

**Comment by NX721** [comment] 2021-02-28 23:36
`_.player.appereance.hairStyle = 25;

_.player.appearancehasChanged.true;` 
Maybe?

**Comment by BrittanyG1150** [comment] 2021-03-01 00:32
mhm what do I do with that?

**Comment by NX721** [comment] 2021-03-01 01:30
Put in console (Ctrl Shift J)

**Comment by BrittanyG1150** [comment] 2021-03-01 02:21
I don't get where im supposed to put that in. Can you send me a screenshot of what im supposed to do or something because i am so confused

**Comment by PatheticMustan** [comment] 2021-03-01 02:30
On windows, press "Control Shift I". On Mac, it's "Control Shift J"

It should bring up a sidebar. On the bottom, is a text field where you can put the code.

![image](https://user-images.githubusercontent.com/35382971/109444852-327a3c80-7a0c-11eb-8ff4-319b53f5d8d1.png)

**Comment by BrittanyG1150** [comment] 2021-03-01 11:17
ohhhh okay thank you so much. I was confused where exactly I had to put the code

**Comment by NX721** [comment] 2021-03-01 21:01
The script i put gives u a secret girl hairstyle change the number for different hairstyles

**Comment by BrittanyG1150** [comment] 2021-03-01 23:37
okay but whenever i put the code, then it just gives me an error

**Comment by PatheticMustan** [comment] 2021-03-02 13:19
Prereq before continuing: #565

**Comment by NameIsA** [comment] 2021-03-03 23:36
add enhancement label

**Comment by PixelMMO** [comment] 2021-03-04 16:16
when i put the code in the console it just gives an error

**Comment by PixelMMO** [comment] 2021-03-04 16:17
what do i do?

**Comment by BoredFishRE** [comment] 2021-03-04 16:19
can you visit https://prodigyhacking.ml

**Comment by PixelMMO** [comment] 2021-03-04 16:19
yes but its just lots of code

**Comment by PixelMMO** [comment] 2021-03-04 16:19
what do i do with that

**Comment by BoredFishRE** [comment] 2021-03-04 16:20
alright hmm

**Comment by BoredFishRE** [comment] 2021-03-04 16:20
is the extension installed?

**Comment by PixelMMO** [comment] 2021-03-04 16:20
the PHEx.zip

**Comment by PixelMMO** [comment] 2021-03-04 16:20
yeah

**Comment by PixelMMO** [comment] 2021-03-04 16:24
it says that that site cant be reached

**Comment by BoredFishRE** [comment] 2021-03-04 16:25
hm, can you visit https://proxy.prodigyhacking.com

**Comment by PixelMMO** [comment] 2021-03-04 16:26
nope

**Comment by PixelMMO** [comment] 2021-03-04 16:26
it says it has insecure content

**Comment by BoredFishRE** [comment] 2021-03-04 16:27
hm weird

**Comment by BoredFishRE** [comment] 2021-03-04 16:27
@ArcerionDev does the extension require the CORS anywhere?

**Comment by ArcerionDev** [comment] 2021-03-04 16:29
wait no scratch that

**Comment by BoredFishRE** [comment] 2021-03-04 16:29
Yes or no?

**Comment by ArcerionDev** [comment] 2021-03-04 16:29
no

**Comment by BoredFishRE** [comment] 2021-03-04 16:30
alright

**Comment by PixelMMO** [comment] 2021-03-04 16:30
i disabled the proxy and its still not working

**Comment by PixelMMO** [comment] 2021-03-04 16:32
i ran diagnostics and it says that there is a problem with local networks

**Comment by BoredFishRE** [comment] 2021-03-04 16:32
that shouldn't make a difference.

**Comment by PixelMMO** [comment] 2021-03-04 16:33
would you be able to send the download through this chat?

**Comment by PatheticMustan** [comment] 2021-03-04 17:30
Please continue this in discussions.... this is what it's for, after all...

**Comment by PatheticMustan** [comment] 2021-03-09 19:34
(i was the one that wrote that but ok)

the issue is here to put it in WCM

**Comment by NX721** [comment] 2021-03-18 19:07
Apparently, there isn't any secret male hairstyles, but there are a few for female.

**Comment by PatheticMustan** [comment] 2021-03-19 12:35
Possibly related
https://gist.github.com/PatheticMustan/8986e95884f78a22da9958624d597019

**Comment by Idk-prog527** [comment] 2021-05-29 00:53
I think first you ctrl + shift + i (Or ctrl + shift + j for mac) then, click on console, type in some gibberish into the search bar in there so that it will all be cleared, copy/paste in that code you got there, and then it will work. (P.S: if you do not have PHEx and try to do this, it will give you a 404 message, and if you have PHEx, you can do these steps clearly.)

**Comment by Jeremiah66268** [comment] 2021-06-16 16:56
How do we get different hair but with a chromebook?

**Comment by PatheticMustan** [comment] 2021-06-16 21:40
control shift i to open console

**Comment by hostedposted** [comment] 2021-06-16 21:41
https://user-images.githubusercontent.com/70211235/122297867-06ef6500-ceca-11eb-9554-71cc92394d08.mp4

**Comment by Phenomenon1337** [comment] 2021-07-07 16:55
can.. i close this now?

**Closed** 2021-08-11 15:41 UTC
Labels: Enhancement, Hack
