### ISSUE TITLE
[HR] Walk thru walls.

### ISSUE THREAD

**Issue by hellonearth311** [Prodigy-Hacking/ProdigyMathGameHacking#770] opened 2021-03-19 15:24 UTC
**Describe the hack in 5 words or less:**
Walking thru walls.

**(Optional) Additional information**
Make a WCM toggler that when enabled, lets you walk thru anything.

**Have you made sure this hack isn't available yet?* (Yes/No)**
Yes.

**Comment by NX721** [comment] 2021-03-19 15:42
You mean walk through game borders, and that might be confusing for other players, but we'll look into it.

**Comment by PatheticMustan** [comment] 2021-03-20 18:48
dupe of #624

**Closed by PatheticMustan** 2021-03-20 18:48 UTC
