### ISSUE TITLE
[BUG]dropdown arrow not showing

### ISSUE THREAD

**Issue by butterflybob** [Prodigy-Hacking/ProdigyMathGameHacking#1265] opened 2022-01-11 20:38 UTC
the arrow to load the menu isn't showing so i can't access the hacks

**Comment by afkvido** [comment] 2022-01-11 21:10
That's not a bug, you've just set something up incorrectly.
Go to our [discord server](discord.gg/XQDfbfq) to get support.

**Comment by 32n** [comment] 2022-01-11 21:59
@butterflybob please give us more information on how you set up the hacks to reproduce this bug and screenshot/paste any console errors you get. This could be a mistake on your end, and could be caused by a variety of things.

**Comment by butterflybob** [comment] 2022-01-12 21:23
the video on the extension just said to download it

**Comment by 32n** [comment] 2022-01-12 21:29
Are you getting any console errors? Make sure the extension is activated and send us a screenshot of your console please.

**Comment by butterflybob** [comment] 2022-01-12 21:34
i just downloaded the extension and its on no errors

**Comment by 32n** [comment] 2022-01-12 21:39
Could you please send a screenshot of your console?

**Comment by butterflybob** [comment] 2022-01-12 21:53
and what do you mean by console?

**Comment by 32n** [comment] 2022-01-12 22:58
Ok I'm going to close this issue. It's very likely that this is an issue on your part. Please do what afkvido said:

> That's not a bug, you've just set something up incorrectly.
> Go to our [discord server](discord.gg/XQDfbfq) to get support.

**Closed by 32n** 2022-01-12 22:58 UTC
Labels: Bug, Waiting on info
