### ISSUE TITLE
[BUG] Epic arena broken

### ISSUE THREAD

**Issue by PixelMMO** [Prodigy-Hacking/ProdigyMathGameHacking#577] opened 2021-03-02 15:42 UTC
***Description***:
when i try to enter the epic arena it shows the animation but doesnt teleport me (it still doesnt work when i press fix battle crash)

***Replication***:
just try to enter the epic arena

***Additional Errors***:
morphing still crashes even if you press fix morph crash

**Comment by irhrhd** [comment] 2021-03-02 16:17
If you have your epic on your team it wont work for that epic

**Comment by ArcerionDev** [comment] 2021-03-02 16:18
can you send a screenshot of the error @PixelMMO

**Comment by PixelMMO** [comment] 2021-03-02 16:19
im on a chromebook idk how to send a screen shot

**Comment by PixelMMO** [comment] 2021-03-02 16:22
![image](https://user-images.githubusercontent.com/79719521/109679449-95bdb900-7b49-11eb-8e99-555657662b7c.png)

**Comment by PixelMMO** [comment] 2021-03-02 16:23
when i press start it shows the animation but it doesnt work

**Comment by irhrhd** [comment] 2021-03-02 16:23
Is luma on your battle team?

**Comment by PixelMMO** [comment] 2021-03-02 16:24
yes

**Comment by PixelMMO** [comment] 2021-03-02 16:24
![image](https://user-images.githubusercontent.com/79719521/109679774-e33a2600-7b49-11eb-8714-e7fe1825879c.png)

**Comment by irhrhd** [comment] 2021-03-02 16:25
Remove luma then try you cant have them on your team its a glitch

**Comment by ArcerionDev** [comment] 2021-03-02 16:25
> im on a chromebook idk how to send a screen shot

Ctrl + Shift + 
![image](https://user-images.githubusercontent.com/60945964/109679906-fe0c9a80-7b49-11eb-84cf-24bd82c2295a.png)

**Comment by PixelMMO** [comment] 2021-03-02 16:25
its still not working even if i dont have luma on my team

**Comment by irhrhd** [comment] 2021-03-02 16:26
Remove her as a buddie too

**Comment by ArcerionDev** [comment] 2021-03-02 16:27
that doesn't do anything

**Comment by PixelMMO** [comment] 2021-03-02 16:27
still not working

**Comment by ArcerionDev** [comment] 2021-03-02 16:27
send your console please

**Comment by irhrhd** [comment] 2021-03-02 16:27
Hmm idk then

**Comment by ArcerionDev** [comment] 2021-03-02 16:27
![image](https://user-images.githubusercontent.com/60945964/109680185-4461f980-7b4a-11eb-9b38-87103e639907.png)

**Comment by PixelMMO** [comment] 2021-03-02 16:27
its also not working for my friend and hes trying it with tidus

**Comment by ArcerionDev** [comment] 2021-03-02 16:28
please send a screenshot of your console

**Comment by PixelMMO** [comment] 2021-03-02 16:28
![image](https://user-images.githubusercontent.com/79719521/109680306-622f5e80-7b4a-11eb-91b1-2d1d50601d7c.png)

**Comment by irhrhd** [comment] 2021-03-02 16:28
Hmm thats wierd It happened to me too but i just removed them then it fixed

**Comment by ArcerionDev** [comment] 2021-03-02 16:29
alright this is odd, I'll try to duplicate

**Comment by PixelMMO** [comment] 2021-03-02 16:29
the swirl animation shows but it doesnt teleport me

**Comment by ArcerionDev** [comment] 2021-03-02 16:30
confirmed

**Comment by PixelMMO** [comment] 2021-03-02 16:31
?

**Comment by PixelMMO** [comment] 2021-03-02 16:31
ok

**Comment by ArcerionDev** [comment] 2021-03-02 16:31
will work on asap

**Comment by PixelMMO** [comment] 2021-03-02 16:31
ty

**Comment by irhrhd** [comment] 2021-03-02 16:32
![4820CC40-5D5E-4B1A-87C2-9A3D5B8AA675](https://user-images.githubusercontent.com/62729648/109680883-c8f44e00-7b31-11eb-8127-e0c359f2ab88.png)
![C1A3E531-2101-4A83-9311-BEB29B8A602D](https://user-images.githubusercontent.com/62729648/109680899-cbef3e80-7b31-11eb-95fd-d10ca7c9e86c.png)
![A5C99FEB-8E70-44D3-8144-EC8984E18752](https://user-images.githubusercontent.com/62729648/109680907-cdb90200-7b31-11eb-944d-e19e0d8302db.png)
Works for me perfectly fine

**Comment by PixelMMO** [comment] 2021-03-02 16:33
i put everything to how you have it and is still not working

**Comment by ArcerionDev** [comment] 2021-03-02 16:34
yeah I see, we'll try and solve this soon

**Comment by PixelMMO** [comment] 2021-03-02 16:34
thank you

**Comment by irhrhd** [comment] 2021-03-02 16:37
It probably works for me because there was an old prodigy hacking that was made last year that i joined in march of last year but im pretty sure it was taken down so yeah and the hacks on this were used last year that was the last time this account was hacked

**Comment by PatheticMustan** [comment] 2021-03-02 19:09
Ah, @ArcerionDev could you explain the problem

**Comment by ArcerionDev** [comment] 2021-03-02 19:09
I don't *know* the problem

**Comment by PixelMMO** [comment] 2021-03-03 14:36
the problem is that when i try to teleport to the epic arena the animation shows but it never teleports you to the arena

**Comment by PixelMMO** [comment] 2021-03-03 14:37
@PatheticMustan

**Comment by NameIsA** [comment] 2021-03-03 15:00
will try to work on this soon

**Comment by PixelMMO** [comment] 2021-03-03 15:10
ty

**Comment by NameIsA** [comment] 2021-03-03 15:43
ashjksaasjjasad ok time to start

**Comment by NameIsA** [comment] 2021-03-03 15:44
free account i dont need
![image](https://user-images.githubusercontent.com/61570792/109831372-3b2d6700-7bf4-11eb-9296-1848d75c3553.png)

**Comment by PatheticMustan** [comment] 2021-03-03 15:51
replicated

**Comment by PatheticMustan** [comment] 2021-03-03 15:58
line 95652-95663 in 3-18-4

**Comment by PatheticMustan** [comment] 2021-03-03 15:59
somewhere it's trying to load assets that don't exist
![image](https://user-images.githubusercontent.com/35382971/109833656-71c4ab00-7c0f-11eb-97cb-6f68d0fa288c.png)

**Comment by PatheticMustan** [comment] 2021-03-03 16:00
L95660, 3-18-4
```
this._assets = t.getAssets(this.game, o.screenName, o.teamA, o.teamB, c.a.instance.prodigy.gameContainer.get("f6e-0e55"), a.backgroundMusic)
```

**Comment by NameIsA** [comment] 2021-03-03 16:04
hmm it let me battle

**Comment by PatheticMustan** [comment] 2021-03-03 16:04
I think it's trying to fetch a number

**Comment by NameIsA** [comment] 2021-03-03 16:10
weird it didnt happen in my new account

**Comment by PatheticMustan** [comment] 2021-03-03 16:16
pets added with add pet don't work....?
![Uploading image.png…]()

**Comment by NameIsA** [comment] 2021-03-03 16:20
i used get all pets and it seemed to work

**Comment by PatheticMustan** [comment] 2021-03-03 16:24
@NameIsA, were you able to enter the epic arena? It seems like the entire thing is deprecated

**Comment by ArcerionDev** [comment] 2021-03-03 16:25
maybe get rid of "get all epics" because epics are included in get all pets

**Comment by PatheticMustan** [comment] 2021-03-03 16:27
;-; i'm not smart enough to rev how prodigy gets and caches its assets,unless @NameIsA has already opened the battle, I'll close this issue

**Comment by NameIsA** [comment] 2021-03-03 16:31
> @NameIsA, were you able to enter the epic arena? It seems like the entire thing is deprecated

yes i was and i did a battle

**Comment by PatheticMustan** [comment] 2021-03-03 16:31
hell

**Comment by PixelMMO** [comment] 2021-03-03 17:15
il still not able to open epic arena

**Comment by PixelMMO** [comment] 2021-03-03 17:15
im still not able to open the epic arena, i even tried making a new account

**Comment by NameIsA** [comment] 2021-03-03 17:19
tf this is weirdddd

**Comment by irhrhd** [comment] 2021-03-03 17:20
NameIsA think you can help me make a proxy

**Comment by PixelMMO** [comment] 2021-03-03 17:26
https://share.vidyard.com/watch/DAPqA1gn1xLHLdyfrTteUo?

**Comment by PixelMMO** [comment] 2021-03-03 17:26
thats what happens

**Comment by PixelMMO** [comment] 2021-03-03 17:27
https://share.vidyard.com/watch/DAPqA1gn1xLHLdyfrTteUo?

**Comment by PixelMMO** [comment] 2021-03-03 17:28
thats what happens when i try to enter the arena

**Comment by PixelMMO** [comment] 2021-03-03 17:29
@ArcerionDev watch this
https://share.vidyard.com/watch/DAPqA1gn1xLHLdyfrTteUo?
thats what happens for me

**Comment by PixelMMO** [comment] 2021-03-03 17:33
i tried in a public server but it still didnt work

**Comment by PixelMMO** [comment] 2021-03-03 17:54
btw about the **morph crash issue** the error is that when the game tries to load the sprite of the morph the game crashes, i found this out by going to harmony island and morphing because harmony island has the sprite for the wizard saved so you cant morph so when you force a morph it doesn't show.

heres a video
https://share.vidyard.com/watch/PGfmwZvi9djF5kEvwWPjn9?

**Comment by BETPRODIGYHACKER** [comment] 2021-05-24 18:19
cool

**Comment by BETPRODIGYHACKER** [comment] 2021-06-09 18:51
gaaaa

**Comment by 4evera1one** [comment] 2021-07-07 17:54
ill... look into this?

**Comment by PatheticMustan** [comment] 2021-07-10 04:28
cool.

**Comment by 4evera1one** [comment] 2021-07-13 17:57
i think it works now, i can play any epic arena battle thingy

**Comment by LeoBadeaux** [comment] 2021-08-11 15:59
> i think it works now, i can play any epic arena battle thingy

alright closed then

**Closed** 2021-08-11 15:59 UTC
Labels: Bug, Help needed, Research, PatchFix, Priority: Medium, Confirmed
