### ISSUE TITLE
List of everything that can trigger 418, in 1 issue.

### ISSUE THREAD

**Issue by Erisfiregamer1** [Prodigy-Hacking/ProdigyMathGameHacking#1272] opened 2022-01-14 02:08 UTC
Here's some things to avoid while using the hacks!
- Atempting to go over or to 10m gold (prodigy has a 10m gold cap, if it is gone over by ANY means the game 418s and rolls you back. WCM also has a cap of 10m too, so don't bypass it...)
- Trying to get the OG Epic buddies (but not the pets?? what)
- Other stuff I'm unaware of (comment and I'll confirm it)

**Comment by RtypeX** [comment] 2022-01-14 02:11
ok

**Comment by PatheticMustan** [comment] 2022-01-14 04:47
again clarifying that PHEx does not actually do anything besides injecting the cheats. I think you mean WCM

**Comment by afkvido** [comment] 2022-01-14 05:56
people get those confused a lot

> again clarifying that PHEx does not actually do anything besides injecting the cheats. I think you mean WCM

**Comment by afkvido** [comment] 2022-01-14 06:01
@Erisfiregamer1

List of everything that can trigger 418 (and more), in 1 entire respsitory

https://github.com/afkvido/prodigyErrCodes


###### why the hell did I do this

**Comment by Erisfiregamer1** [comment] 2022-01-14 12:37
> @Erisfiregamer1
> 
> List of everything that can trigger 418 (and more), in 1 entire respsitory
> 
> https://github.com/afkvido/prodigyErrCodes
> 
> ###### why the hell did I do this

Cool.

**Comment by hellonearth311** [comment] 2022-01-27 20:49
Close all popups can easily fix 418, then inactivity error will show, again close all popups.

**Comment by afkvido** [comment] 2022-01-27 21:04
> Close all popups can easily fix 418, then inactivity error will show, again close all popups.

Your character won't save...

**Comment by donaldli2020** [comment] 2022-01-28 00:17
> > Close all popups can easily fix 418, then inactivity error will show, again close all popups.
> 
> Your character won't save...

error 403

**Comment by ArcerionDev** [comment] 2022-02-01 01:48
concept is a duplicate of #1154

**Closed by ArcerionDev** 2022-02-01 01:48 UTC
