### ISSUE TITLE
[HR] Ultimate Membership

### ISSUE THREAD

**Issue by afkvido** [Prodigy-Hacking/ProdigyMathGameHacking#1234] opened 2021-12-18 21:14 UTC
**Describe your hack:**
We only have the basic membership hack right now. Please add an ultimate membership toggler.

**(Optional) Additional information**

**Have you made sure this hack isn't available yet?* (Yes/No)**
Yes. we only have basic membership

**Comment by donaldli2020** [comment] 2021-12-18 23:24
We've reached #1234! What a cool number!

**Comment by donaldli2020** [comment] 2021-12-18 23:25
Ok, I think think this can be possible because you have the basic membership.

**Comment by afkvido** [comment] 2021-12-18 23:46
> We've reached #1234! What a cool number!

ayyyyy

**Comment by afkvido** [comment] 2021-12-18 23:46
> Ok, I think think this can be possible because you have the basic membership.

wonderful!

**Comment by donaldli2020** [comment] 2021-12-19 00:58
sorry for 2 thinks

**Comment by donaldli2020** [comment] 2021-12-19 00:59
Maybe try:
```
_.instance.prodigy.gameContainer.get("98e-4ed0").data.membership.active = true;
_.instance.prodigy.gameContainer.get("98e-4ed0").data.egInfo.tier = 3;
```

**Comment by donaldli2020** [comment] 2021-12-19 01:00
We have a dupe of #1174

**Comment by afkvido** [comment] 2021-12-19 23:54
> We have a dupe of #1174 

oops

**Comment by 32n** [comment] 2021-12-20 01:19
duplicate.

**Closed by 32n** 2021-12-20 01:19 UTC

**Comment by afkvido** [comment] 2022-01-06 03:42
> Maybe try:
> 
> ```
> _.instance.prodigy.gameContainer.get("98e-4ed0").data.membership.active = true;
> _.instance.prodigy.gameContainer.get("98e-4ed0").data.egInfo.tier = 3;
> ```

just pasting that doesn't work.
