### ISSUE TITLE
Spells and level saves not saving

### ISSUE THREAD

**Issue by PixelMMO** [Prodigy-Hacking/ProdigyMathGameHacking#566] opened 2021-03-01 15:21 UTC
***Description***:
when i try to change the spells on my pets it doesnt show the spells i chose when i enter a battle

***Replication***:
to replicate the bug just change the spells on any pet and enter a battle, the spells are the normal spells

***Additional Errors***:
when i try to set my lvl to 1e+100 it justs reverts back to lvl 100 when i re enter the menu

**Comment by CRobbins0867** [comment] 2021-03-01 16:24
@PixelMMO well i dont know about the other things but the level if you don't have to cheat menu enabled the max is 100

**Comment by ArcerionDev** [comment] 2021-03-01 16:25
Oh yeah, levels over 100 do revert themselves back to 100 on reloading, will fix

**Comment by PixelMMO** [comment] 2021-03-01 19:06
ok ty

**Comment by NX721** [comment] 2021-03-02 07:04
You can set your level to Infinity you know

**Comment by PatheticMustan** [comment] 2021-03-02 13:14
No

**Comment by PixelMMO** [comment] 2021-03-02 15:44
you can set it to infinity you just have to add 500 nines

**Comment by PatheticMustan** [comment] 2021-03-02 15:46
That's not the issue here, changing your level beyond 100 has unexpected side effects.

**Comment by achen6196** [comment] 2021-03-03 14:28
So y'all gonna fix the levels reverting back to lvl 100?

**Comment by MelonMan101** [comment] 2021-03-03 14:30
> So y'all gonna fix the levels reverting back to lvl 100?

give them time, they will figure something out.

**Comment by PatheticMustan** [comment] 2021-03-03 15:12
> So y'all gonna fix the levels reverting back to lvl 100?

no, it's not a bug, it's a feature ;))

**Comment by YamaHacks** [comment] 2021-03-11 23:32
> > So y'all gonna fix the levels reverting back to lvl 100?
> 
> no, it's not a bug, it's a feature ;))

bugs? in WCM? nah, those are just "fun easter eggs"

**Comment by ArcerionDev** [comment] 2021-03-11 23:33
> > > So y'all gonna fix the levels reverting back to lvl 100?
> > 
> > 
> > no, it's not a bug, it's a feature ;))
> 
> bugs? in WCM? nah, those are just "fun easter eggs"

why don't you fix them then instead of complaining about them

**Comment by PatheticMustan** [comment] 2021-03-11 23:42
no but seriously, this is legitimately a feature, we don't want people setting their levels above 100 and complaining when it doesn't work

**Comment by ArcerionDev** [comment] 2021-03-11 23:48
perhaps we should store the level in localstorage

**Comment by ChickenOnYT** [comment] 2021-03-12 15:55
if you dont wanna be assigned unassign yourself

**Comment by ArcerionDev** [comment] 2021-03-12 16:00
this is definitely a serious issue so ye that's cool

**Comment by ArcerionDev** [comment] 2021-03-18 22:41
I have an ok fix, closing until prodigy updates their apis

**Closed by ArcerionDev** 2021-03-18 22:41 UTC
Labels: Bug, Priority: High
