### ISSUE TITLE
[BUG]Rune run won't let me play.

### ISSUE THREAD

**Issue by WillBillDillPickle** [Prodigy-Hacking/ProdigyMathGameHacking#808] opened 2021-03-25 12:14 UTC
***Description***:
Whenever I try to do a rune run, this happens.

***Replication***:

***Images***:
![image](https://user-images.githubusercontent.com/73481552/112471313-1d11dd00-8d42-11eb-9288-556298043dfa.png)

***Additional Errors***:

**Comment by WillBillDillPickle** [comment] 2021-03-25 12:51
Ok. I found out. You can't enter Rune runs with Iligle pets(Pets from the hack.) All of your pets must be ones you got on your own, not from this hack.

**Comment by ChickenOnYT** [comment] 2021-03-25 12:53
wait thats weird

**Comment by ChickenOnYT** [comment] 2021-03-25 12:53
@PatheticMustan

**Comment by WillBillDillPickle** [comment] 2021-03-25 12:58
Who deleated my comment?

**Comment by WillBillDillPickle** [comment] 2021-03-25 12:58
Nvm

**Comment by NX721** [comment] 2021-03-25 14:16
Yes I'm already aware of this lol

**Comment by NX721** [comment] 2021-03-25 14:17
> Ok. I found out. You can't enter Rune runs with Iligle pets(Pets from the hack.) All of your pets must be ones you got on your own, not from this hack.

I'm using 2 Terrosaurs from the hacks, and it seems to be working fine. With Epics, Ummm...

**Comment by WillBillDillPickle** [comment] 2021-03-25 14:28
Then I don't know. Maybe I should try disabling the extension.

**Comment by WillBillDillPickle** [comment] 2021-03-25 14:30
I'm going to try using 2 Peekos from the Add pet hack.

**Comment by WillBillDillPickle** [comment] 2021-03-25 14:31
It still gives me the error.

**Comment by WillBillDillPickle** [comment] 2021-03-25 14:32
I'm going to try two Trip Trops I caught.

**Comment by WillBillDillPickle** [comment] 2021-03-25 14:35
And it works.

**Comment by NX721** [comment] 2021-03-25 14:39
> And it works.

Ok, well that's weird, but I'll enter console and find the errors soon.

**Comment by WillBillDillPickle** [comment] 2021-03-25 14:51
Thanks! My Twin sister also got the same result as me.

**Comment by PatheticMustan** [comment] 2021-03-25 16:30
huh, interesting

**Comment by ArcerionDev** [comment] 2021-03-25 16:31
yeah I'm not sure of the cause of this

**Comment by WillBillDillPickle** [comment] 2021-03-25 16:52
It works now. But I uninstalled the extension. (The extension somehow automatically got uninstalled.)

**Comment by WillBillDillPickle** [comment] 2021-03-25 16:52
I'm going to install it again.

**Comment by WillBillDillPickle** [comment] 2021-03-25 17:17
OMG Rune Run works now.

**Comment by WillBillDillPickle** [comment] 2021-03-25 17:17
It works even with the extension on.

**Comment by WillBillDillPickle** [comment] 2021-03-25 18:00
Wait- it doesn't work anymore. :(

**Comment by WillBillDillPickle** [comment] 2021-03-26 00:15
Can somebody investigate this? (Like reading the code)

**Comment by PatheticMustan** [comment] 2021-03-26 12:08
Not sure where to start...

**Comment by WillBillDillPickle** [comment] 2021-03-26 15:22
Can someone use the Add pet feature and add a pet that they have never own? Then, use that per in Rune run. It shouldn't let you play. I found something out guys, When you Add Pet, the pet doesn't appear that you own it in your pet book(not pet inventory.)

**Comment by NX721** [comment] 2021-03-26 18:04
> It works now. But I uninstalled the extension. (The extension somehow automatically got uninstalled.)

Yes, if you did it manually, It will delete when you shut down/restart your device.

**Comment by WillBillDillPickle** [comment] 2021-04-02 15:15
I know what to fix. Make it so when you use the "Add pet hack", the pet you added will also be shown as you own it on your pet book. When I add pet, it is in my Pet inv, but it appears as if I have never even encountered it in my Pet book.

**Comment by lichessgoodchesscombad** [comment] 2021-04-08 15:40
i know why, you edited the pets

**Comment by PatheticBurger** [comment] 2021-04-19 17:12
@lichessgoodchesscombad chess.com good

**Comment by YamaHacks** [comment] 2021-04-24 00:54
Has anyone been able to reproduce this? works fine for me

**Comment by ArcerionDev** [comment] 2021-06-05 14:48
Alright, figured out the reason for this, when you get runes via hacking, you can't equip them in rune runs without the game acting up.
There are currently rune hacks that do work, more or less, so closing this for now.

**Closed by ArcerionDev** 2021-06-05 14:48 UTC
Labels: Bug
